
spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    eureka-server-connect-timeout-seconds: 5
    enabled: true
    fetch-registry: false
    register-with-eureka: false
