
spring:
  application:
    name: espark-configuration-server
  cloud:
    config:
      server:
        git:
          #uri: file://${user.home}/config-repo
          uri: https://github.com/adarshkumarsingh83/config-repo
          default-label: main
          skipSslValidation: true
          timeout: 4


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090