
spring:
  application:
    name: espark-configuration-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          default-label: master


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090