
spring:
  application:
    name: espark-api-aggregator
  config:
    import: configserver:http://localhost:8090
    activate:
      on-profile: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    context-path: /api
  port: 0

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---
spring:
  application:
    name: espark-api-aggregator
  config:
    import: configserver:http://localhost:8090
    activate:
      on-profile: development

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    context-path: /api
  port: 0

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
---

spring:
  application:
    name: espark-api-aggregator
  config:
    import: configserver:http://localhost:8090
    activate:
      on-profile: kubernates

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    context-path: /api
  port: 0

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans