
spring:
  application:
    name: espark-api-aggregator
  config:
    import: configserver:http://localhost:8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    context-path: /api
  port: 0
