server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  security:
    user:
      name: rootname
      password: rootpwd
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/adarshkumarsingh83/config-repo/
         # uri: file://${user.home}/config-repo

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true