spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adarshkumarsingh83/configuration.git
          searchPaths: espark-configurations


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka