hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000

spring:
  application:
    name: api-gateway
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: service-one
        uri: lb://EUREKA-CLIENT-ONE
        filters:
          - AddRequestHeader=X-ONE-HEADER,first-service-header
        predicates:
          - Path=/service-one/**
      - id: service-two
        uri: lb://EUREKA-CLIENT-TWO
        filters:
          - AddRequestHeader=X-TWO-HEADER,second-service-header
        predicates:
          - Path=/service-two/**
    corsConfigurations:
      '[/**]':
        allowedOrigins: "http://localhost:3000"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream