
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: service-one
          uri: lb://SPRING-CLOUD-CLIENT-SERVICE
          predicates:
            - Path=/api/wish/**
        - id: service-two
          uri: lb://SPRING-CLOUD-CLIENT-SERVICE
          predicates:
            - Path=/api/wish/**