
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: address-service
          uri: http://localhost:8081/
          predicates:
            - Path=/address/**
          filters:
            - name: GlobalFilter
            - name: PreFilter
            - name: PostFilter
            - AddRequestHeader=X-Request-ESPARK, ESPARK-ADDRESS-REQEST
            - AddResponseHeader=X-Response-ESPARK, ESPARK-ADDRESS-RESPONSE
        - id: employee-service
          uri: http://localhost:8082/
          predicates:
            - Path=/employee/**
          filters:
            - name: GlobalFilter
            - name: PreFilter
            - name: PostFilter
            - AddRequestHeader=X-Request-ESPARK, ESPARK-EMPLOYEE-REQEST
            - AddResponseHeader=X-Response-ESPARK, ESPARK-EMPLOYEE-RESPONSE