management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    instances:
      dataService:
        limit-for-period: 2
        limit-refresh-period: 5s
        timeout-duration: 0