spring:
  application:
    name: espark-api-gateway-diclarative
  cloud:
    gateway:
      actuator:
        verbose:
          enabled: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: first
          uri: lb://ESPARK-API-AGGREGATOR
          predicates:
            - Path=/api/wish/**
          filters:
            - AddRequestHeader=wish-request, wish-request-header
            - AddResponseHeader=wish-response, wish-response-header
        - id: second
          uri: lb://ESPARK-API-AGGREGATOR
          predicates:
            - Path=/api/greet/**
          filters:
            - AddRequestHeader=greet-request, greet-request-header
            - AddResponseHeader=greet-response, greet-response-header

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080