FROM openjdk:8
MAINTAINER adarshkumarsingh83@gmail.com
ADD target/springboot-micrometer-prometheus-grafana.jar springboot-micrometer-prometheus-grafana.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","springboot-micrometer-prometheus-grafana.jar"]