version: '3.7'

services:

  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

  springboot-micrometer-prometheus-grafana:
    container_name: springboot-micrometer-prometheus-grafana
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:5
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8080:8080"
    links:
      - grafana
    networks:
      monitoring:
        aliases:
          - springboot-micrometer-prometheus-grafana

networks:
  monitoring: